# Generated by Django 5.2.7 on 2025-10-08 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('tanggal_pengaduan', models.DateTimeField(auto_now_add=True)),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='warga.warga')),
            ],
        ),
    ]
