# Generated by Django 5.2.7 on 2025-10-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduan',
            old_name='isi',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='pengaduan',
            old_name='tanggal_pengaduan',
            new_name='tanggal_lapor',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='BARU', max_length=10),
        ),
    ]
